parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # Controllers
  App\Shipping\Infrastructure\Controller\:
    resource: "../src/Shipping/Infrastructure/Controller/"
    tags: ["controller.service_arguments"]

  # Buses
  App\Shared\Domain\Bus\Command\CommandBusInterface: '@App\Shared\Infrastructure\Bus\Command\SymfonyMessengerCommandBus'
  App\Shared\Infrastructure\Bus\Command\SymfonyMessengerCommandBus:
    arguments:
      $commandBus: "@command.bus"

  App\Shared\Domain\Bus\Query\QueryBusInterface: '@App\Shared\Infrastructure\Bus\Query\MessengerQueryBus'
  App\Shared\Infrastructure\Bus\Query\MessengerQueryBus:
    arguments:
      $queryBus: "@query.bus"

  App\Shared\Domain\Bus\EventBusInterface: '@App\Shared\Infrastructure\Bus\Event\MessengerEventBus'
  App\Shared\Infrastructure\Bus\Event\MessengerEventBus:
    arguments:
      $eventBus: "@event.bus"
